### ISSUE TITLE
Issues with Vite and ES6

### ISSUE THREAD

**Issue by clibu** [mkkhedawat/frowser#7]
I tried importing frowser various ways and Vite complained about the main entry point in package.json being wrong. Sorry I've moved on and don't have the exact error message any more.

**Comment by mkkhedawat** [comment]
Do you at-least have version or steps on how to re-produce ?

**Comment by nevf** [comment]
Sorry no, I had to move on. I assume it imports ok for you using Vite and ES6 modules.
